  version: '3.8'

  #create a volume for the my sql container.To ensure Data persists after my sql container is stopped
  volumes:
    datafiles:

  services:
    #DataBase Service
    database:
      #Pull the latest mysql image
      image: mysql:8.0.33
      #Map port 3306 on the mysql container to port 3306 in the host
      ports:
        - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
      #Specify where the persisted Data should be stored
      volumes:
        - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
        - datafiles:/var/lib/mysql
      restart: always
      #Specify Environment Variables for mysql
      env_file:
        - .env
      environment: 
        - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQLDB_DATABASE}

      #Api  Service
    api:
      build:
        context: .
        #Use the DockerFile in that Directory
        dockerfile: Dockerfile
      #This Service Depends on the database service specifed above
      depends_on: 
        - database
      #Map port 5157 in the docker container to port 5157 in the Api
      ports:
        - $ASPNET_LOCAL_PORT:$ASPNET_DOCKER_PORT
      restart: always
      #Specify Environment Variables for the Api Service
      env_file:
        - .env
      environment: 
        - DBHOST=${DBHOST}
        - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}